// Ignore Spelling: Linq

using System.Text;

using LoreSoft.Blazor.Controls.Extensions;

namespace LoreSoft.Blazor.Controls.Utilities;

/// <summary>
/// Provides functionality to build LINQ expression strings and parameter lists from <see cref="QueryRule"/> objects.
/// Supports custom filter writers for extensibility and validation of query rules.
/// </summary>
public class LinqExpressionBuilder
{
    private static readonly Dictionary<string, Action<StringBuilder, List<object?>, QueryFilter>> _filterWriters = new(StringComparer.OrdinalIgnoreCase);

    /// <summary>
    /// Initializes static filter writers for supported query operators.
    /// </summary>
    static LinqExpressionBuilder()
    {
        _filterWriters.TryAdd(QueryOperators.Contains, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.NotContains, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.StartsWith, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.NotStartsWith, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.EndsWith, WriteStringFilter);
        _filterWriters.TryAdd(QueryOperators.NotEndsWith, WriteStringFilter);

        _filterWriters.TryAdd(QueryOperators.Equal, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.NotEqual, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.GreaterThan, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.GreaterThanOrEqual, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.LessThan, WriteStandardFilter);
        _filterWriters.TryAdd(QueryOperators.LessThanOrEqual, WriteStandardFilter);

        _filterWriters.TryAdd(QueryOperators.IsNull, WriteNullFilter);
        _filterWriters.TryAdd(QueryOperators.IsNotNull, WriteNullFilter);
    }

    /// <summary>
    /// Registers a custom filter writer for a specific query operator.
    /// </summary>
    /// <param name="operator">The query operator to register.</param>
    /// <param name="writer">The writer action to use for the operator.</param>
    public static void RegisterWriter(string @operator, Action<StringBuilder, List<object?>, QueryFilter> writer)
    {
        _filterWriters[@operator] = writer;
    }

    /// <summary>
    /// Determines whether the specified <see cref="QueryRule"/> is valid for building an expression.
    /// </summary>
    /// <param name="queryRule">The query rule to validate.</param>
    /// <returns><c>true</c> if the rule is valid; otherwise, <c>false</c>.</returns>
    public static bool IsValid(QueryRule? queryRule)
    {
        if (queryRule is QueryGroup group)
            return IsValid(group);

        if (queryRule is QueryFilter filter)
            return IsValid(filter);

        return false;
    }

    /// <summary>
    /// Determines whether the specified <see cref="QueryGroup"/> is valid for building an expression.
    /// </summary>
    /// <param name="queryGroup">The query group to validate.</param>
    /// <returns><c>true</c> if the group is valid; otherwise, <c>false</c>.</returns>
    public static bool IsValid(QueryGroup? queryGroup)
    {
        if (queryGroup == null || queryGroup.Filters.Count == 0)
            return false;

        return queryGroup.Filters.Any(IsValid);
    }

    /// <summary>
    /// Determines whether the specified <see cref="QueryFilter"/> is valid for building an expression.
    /// </summary>
    /// <param name="queryFilter">The query filter to validate.</param>
    /// <returns><c>true</c> if the filter is valid; otherwise, <c>false</c>.</returns>
    public static bool IsValid(QueryFilter? queryFilter)
    {
        if (queryFilter == null)
            return false;

        return queryFilter.Field.HasValue();
    }

    private readonly StringBuilder _expression = new();
    private readonly List<object?> _values = [];

    /// <summary>
    /// Gets the list of parameters used in the built LINQ expression.  Generated by <see cref="Build(QueryRule?)"/>.
    /// </summary>
    public IReadOnlyList<object?> Parameters => _values;

    /// <summary>
    /// Gets the LINQ expression string built from the query rule. Generated by <see cref="Build(QueryRule?)"/>.
    /// </summary>
    public string Expression => _expression.ToString();

    /// <summary>
    /// Builds a LINQ expression string and parameter list from the specified <see cref="QueryRule"/>.
    /// Expression will be updated with the generated LINQ expression.
    /// Parameters will also be updated with the values used in the expression.
    /// </summary>
    /// <param name="queryRule">The query rule to build the expression from.</param>
    public void Build(QueryRule? queryRule)
    {
        _expression.Length = 0;
        _values.Clear();

        if (queryRule == null)
            return;

        Visit(queryRule);
    }

    /// <summary>
    /// Visits the specified <see cref="QueryRule"/> and writes its expression.
    /// </summary>
    /// <param name="queryRule">The query rule to visit.</param>
    private void Visit(QueryRule queryRule)
    {
        if (queryRule == null)
            return;

        if (queryRule is QueryGroup group)
            WriteGroup(group);
        else if (queryRule is QueryFilter filter)
            WriteExpression(filter);
    }

    /// <summary>
    /// Writes a group expression for the specified <see cref="QueryGroup"/>.
    /// </summary>
    /// <param name="entityFilter">The query group to write.</param>
    private void WriteGroup(QueryGroup entityFilter)
    {
        var filters = entityFilter.Filters;

        if (filters == null || filters.Count == 0)
            return;

        var logic = entityFilter.Logic.IsNullOrWhiteSpace()
            ? QueryLogic.And
            : entityFilter.Logic;

        var wroteFirst = false;

        _expression.Append('(');
        foreach (var filter in filters)
        {
            if (wroteFirst)
                _expression.Append(' ').Append(logic).Append(' ');

            Visit(filter);
            wroteFirst = true;
        }
        _expression.Append(')');
    }

    /// <summary>
    /// Writes an expression for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="filter">The query filter to write.</param>
    private void WriteExpression(QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Field))
            return;

        // default comparison equal
        var comparison = filter.Operator;
        if (comparison.IsNullOrEmpty())
            comparison = QueryOperators.Equal;

        if (_filterWriters.TryGetValue(comparison, out var action))
            action(_expression, _values, filter);
        else
            WriteStandardFilter(_expression, _values, filter);
    }

    /// <summary>
    /// Writes a string-based filter expression (e.g., Contains, StartsWith) for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="parameters">The parameter list to add values to.</param>
    /// <param name="filter">The query filter to write.</param>
    private static void WriteStringFilter(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Field))
            return;

        int index = parameters.Count;

        var field = filter.Field;
        var value = filter.Value;

        var method = filter.Operator switch
        {
            QueryOperators.StartsWith => "StartsWith",
            QueryOperators.NotStartsWith => "StartsWith",
            QueryOperators.EndsWith => "EndsWith",
            QueryOperators.NotEndsWith => "EndsWith",
            QueryOperators.Contains => "Contains",
            QueryOperators.NotContains => "Contains",
            _ => "Contains"
        };

        var negation = filter.Operator switch
        {
            QueryOperators.NotContains => true,
            QueryOperators.NotStartsWith => true,
            QueryOperators.NotEndsWith => true,
            _ => false
        };

        builder
            .Append(field)
            .Append(" != NULL && ")
            .AppendIf("!", negation)
            .Append(field)
            .Append('.')
            .Append(method)
            .Append("(@")
            .Append(index)
            .Append(')');

        parameters.Add(value);
    }

    /// <summary>
    /// Writes a standard comparison filter expression (e.g., ==, !=, &gt;, &lt;) for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="parameters">The parameter list to add values to.</param>
    /// <param name="filter">The query filter to write.</param>
    private static void WriteStandardFilter(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Field))
            return;

        int index = parameters.Count;

        var field = filter.Field;
        var value = filter.Value;

        var comparison = filter.Operator switch
        {
            QueryOperators.Equal => "==",
            QueryOperators.NotEqual => "!=",
            QueryOperators.GreaterThan => ">",
            QueryOperators.GreaterThanOrEqual => ">=",
            QueryOperators.LessThan => "<",
            QueryOperators.LessThanOrEqual => "<=",
            _ => "=="
        };

        builder
            .Append(field)
            .Append(' ')
            .Append(comparison)
            .Append(" @")
            .Append(index);

        parameters.Add(value);
    }

    /// <summary>
    /// Writes a null-check filter expression (e.g., IsNull, IsNotNull) for the specified <see cref="QueryFilter"/>.
    /// </summary>
    /// <param name="builder">The <see cref="StringBuilder"/> to append to.</param>
    /// <param name="parameters">The parameter list to add values to.</param>
    /// <param name="filter">The query filter to write.</param>
    private static void WriteNullFilter(StringBuilder builder, List<object?> parameters, QueryFilter filter)
    {
        // Field required for expression
        if (string.IsNullOrWhiteSpace(filter.Field))
            return;

        int index = parameters.Count;

        var field = filter.Field;
        var value = filter.Value;

        var comparison = filter.Operator switch
        {
            QueryOperators.IsNull => "==",
            QueryOperators.IsNotNull => "!=",
            _ => "=="
        };

        builder
            .Append(field)
            .Append(' ')
            .Append(comparison)
            .Append(" NULL");
    }
}
